"""empty message

Revision ID: d41da5f27cf0
Revises: d08ad41dc4f8
Create Date: 2022-07-11 10:32:37.278692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41da5f27cf0'
down_revision = 'd08ad41dc4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('matric_no', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('submitted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'submitted')
    op.drop_column('project', 'matric_no')
    # ### end Alembic commands ###
